name: RVW CLA Agreement
on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types:
      - opened
      - closed
      - synchronize
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: CLA Agreement
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.0.1-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.RVW_WORKFLOWS }}
        with:
          path-to-signatures: '.github/cla/signatures.json'
          path-to-cla-document: 'https://github.com/redvanworkshop/rvw_developers_core/blob/develop/.github/cla/agreement.md'
          branch: 'develop'
          allowlist: manifestinteractive,z1haze,sergeystoma,johnkramlich,bot*
